spring:
  application:
    name: CLONE-BZM-LOUNGE-USER
  profiles:
    active: local
  banner:
    location: classpath:banner.txt
  output:
    ansi:
      enabled: always

logging:
  config: classpath:logback-spring.xml


